services:
  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: host
    container_name: hrm-prometheus
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'